const stageOrder=['幼年期1','幼年期2','成長期','成熟期','完全體','究極體','超究極體'];
let DATA, query='';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function sprite(d){
  const no=String(d.dex_no).padStart(3,'0');
  return `<div class="sprite"><img src="${esc(d.image)}" alt="${esc(d.name_zh)}" loading="lazy" onerror="this.remove();this.parentElement.classList.add('sprite-error');this.parentElement.dataset.no='${no}'"></div>`
}
function conditionRows(e){const items=[['照顧',e.care_mistakes],['努力',e.effort],['戰鬥',e.battles],['勝率',e.win_rate],['時間',e.time]].filter(x=>x[1]&&x[1]!=='-');return items.map(x=>`<div class="condition"><span>${x[0]}</span><strong>${esc(x[1])}</strong></div>`).join('')||'<div class="condition"><span>條件</span><strong>-</strong></div>'}
function matches(d){if(!query)return true;const t=`${d.dex_no} ${d.name_zh} ${d.name_jp} ${d.stage} ${d.attribute}`.toLowerCase();return t.includes(query)}
function renderEvolution(){const root=$('#evolutionView');let html='';for(const stage of stageOrder){const list=DATA.digimon.filter(d=>d.stage===stage&&matches(d));if(!list.length)continue;html+=`<section class="stage"><h2 class="stage-title">${stage}</h2>`;for(const d of list){const routes=DATA.evolutions.filter(e=>e.from===d.name_zh);html+=`<article class="source-card" id="evo-${d.id}"><div class="source-head">${sprite(d)}<div class="name"><h3>#${String(d.dex_no).padStart(3,'0')} ${esc(d.name_zh)}</h3><p>${esc(d.name_jp)}</p></div><div class="badges"><span class="badge">${esc(d.attribute)}</span><span class="badge">睡眠 ${esc(d.sleep_start)}–${esc(d.sleep_end)}</span></div></div><div class="routes">${routes.length?routes.map(e=>`<div class="route"><div class="route-title">→ ${esc(e.to)}</div><div class="conditions">${conditionRows(e)}</div>${e.notes?`<div class="notes">${esc(e.notes)}</div>`:''}</div>`).join(''):'<div class="route">此階段無後續進化資料</div>'}</div></article>`}html+='</section>'}root.innerHTML=html||'<div class="empty">找不到符合項目</div>'}
function renderDex(){const list=DATA.digimon.filter(matches);$('#dexView').innerHTML=list.length?`<div class="dex-grid">${list.map(d=>`<article class="dex-card" data-id="${d.id}">${sprite(d)}<h3>#${String(d.dex_no).padStart(3,'0')} ${esc(d.name_zh)}</h3><p>${esc(d.name_jp)}</p><div class="dex-meta"><span class="badge">${esc(d.stage)}</span><span class="badge">${esc(d.attribute)}</span></div></article>`).join('')}</div>`:'<div class="empty">找不到符合項目</div>';document.querySelectorAll('.dex-card').forEach(x=>x.onclick=()=>{switchView('evolution');setTimeout(()=>document.getElementById('evo-'+x.dataset.id)?.scrollIntoView({behavior:'smooth',block:'start'}),30)})}
function render(){renderEvolution();renderDex()}
function switchView(v){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#evolutionView').classList.toggle('hidden',v!=='evolution');$('#dexView').classList.toggle('hidden',v!=='dex')}
fetch('data/v0.json').then(r=>r.json()).then(d=>{DATA=d;render()}).catch(()=>{$('#evolutionView').innerHTML='<div class="empty">資料載入失敗，請以網站伺服器方式開啟。</div>'});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#searchInput').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();render()});
